[package]
name = "quiklang"
version = "0.1.0"
edition = "2021"

[package.metadata]
quiklang-vm-version = 1

[dependencies]
byteorder = "1.5.0"
criterion = "0.5.1"
rustyline = "9.0.0"
thiserror = "1.0.61"

[build-dependencies]
toml = "0.8.14"

[lib]
name = "quiklang"
path = "src/lib.rs"

[[bin]]
name = "quiklang_bin"
path = "src/bin/main.rs"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"

[[bench]]
name = "tokenize_factorial"
harness = false

[[bench]]
name = "tokenize_large"
harness = false

[[bench]]
name = "run_factorial"
harness = false

[[bench]]
name = "rust_factorial"
harness = false

[[bench]]
name = "interpret_factorial"
harness = false

[[bench]]
name = "bytecode_decode"
harness = false

[[bench]]
name = "bytecode_encode"
harness = false
