[package]
name = "quiklang"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = "0.5.1"

[lib]
name = "quiklang"
path = "src/lib.rs"

[[bin]]
name = "quiklang_bin"
path = "src/bin/main.rs"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"

[[bench]]
name = "tokenize"
harness = false

[[bench]]
name = "tokenize_large"
harness = false